# Generated by Django 3.2.6 on 2021-08-20 02:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('birthday', models.DateField()),
                ('eye_color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('brown', 'Brown'), ('hazel', 'Hazel'), ('gray', 'Gray'), ('dark', 'Dark'), ('other', 'Other')], max_length=10)),
                ('skin_color', models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('olive', 'Olive'), ('fair', 'Fair'), ('pale', 'Pale')], max_length=20)),
                ('height', models.SmallIntegerField()),
                ('shoe_size', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('particularities', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('salary', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_portfolio', to='models.model')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_portfolio', to='models.portfolio')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ModelAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('creation_year', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=512)),
                ('parent_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.modelagency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.SmallIntegerField()),
                ('waist', models.SmallIntegerField()),
                ('hips', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_measures', to='models.model')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
