# Generated by Django 3.2.6 on 2021-08-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210825_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelagency',
            name='slug',
            field=models.SlugField(default='stock-models', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
