# Generated by Django 3.2.6 on 2021-08-30 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_modelagency_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_modelagency', to='models.modelagency'),
            preserve_default=False,
        ),
    ]
