# Generated by Django 3.2.6 on 2021-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20210830_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
