# Generated by Django 3.2.6 on 2021-08-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_model_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Models',
        ),
    ]
