# Generated by Django 3.2.6 on 2021-08-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_model_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='model',
            new_name='measured_model',
        ),
    ]
