# Generated by Django 3.2.6 on 2021-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
